title: Downtime Industries
description: A mostly fictional company for helping you know what to do and not do when writing software. 
theme: just-the-docs

url: https://downtime.industries

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
