title: Downtime Industries
description: A mostly fictional company for helping you know what to do and not do when writing software. 
theme: just-the-docs

url: https://downtime.industries

aux_links:
  Website Repo: https://github.com/downtime-industries/downtime-industries-website

plugins:
  - jekyll-seo-tag

color_scheme: dark